# Project information
site_name: INTERSECTION
site_description: ZUCC INTERSECTION是一个由学生自主发起的，提供浙大城市学院信息资讯的网络信息站。
site_author: Jaycee Chow
site_url: https://lifeinzucc.github.io

# mkdocs basic settings
docs_dir: "docs"
site_dir: "public"
strict: true

# Repository
repo_name: 帮助我们完善这个网站
repo_url: https://github.com/lifeInZUCC/ZUCC-intersection

# Copyright
copyright: "Copyright &copy; 2020 lifeInZUCC organization"

# Configuration
theme:
  name: "material"

  # 404 page
  static_templates:
    - 404.html

  # Changed value
  logo:
    icon: "ZUCC"
  palette:
    primary: "black"
    accent: "deep orange"
  language: "zh"
  feature:
    tabs: true

# Plugins
plugins:
  - search
  - git-revision-date-localized:
      type: iso_date
  - minify:
      minify_html: true

# Customization
extra:
  social:
    - type: "github"
      link: "https://github.com/nonlinearthink"
    - type: "github"
      link: "https://github.com/wangtianyu0222"
  search:
    language: "en, ja"

# Extensions
markdown_extensions:
  - footnotes
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      linenums: false
      guess_lang: false
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  # - meta

extra_javascript:
  - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML"

# Page tree
nav:
  - 简介: index.md
  - 我们的故事: log.md
  - 关于我们的组织: about.md
  - ZUCC课程补全计划:
      - 简介: course/Readme.md
      - 操作系统原理:
          - 导引: course/301258/Readme.md
          - 周测习题集:
              - 第一周: course/301258/resource/week1.md
              - 第二周: course/301258/resource/week2.md
              - 第三周: course/301258/resource/week3.md
              - 第四周: course/301258/resource/week4.md
              - 第五周: course/301258/resource/week5.md
              - 第六周: course/301258/resource/week6.md
              - 第七周: course/301258/resource/week7.md
              - 第九周: course/301258/resource/week9.md
              - 第十周: course/301258/resource/week10.md
              - 第十一周: course/301258/resource/week11.md
              - 第十二周: course/301258/resource/week12.md
              - 第十三周: course/301258/resource/week13.md
              - 第十四周: course/301258/resource/week14.md
              - 第十五周: course/301258/resource/week15.md
          - BB平台习题集:
              - 操作系统基本概念: course/301258/resource/os-basic-concepts.md
              - 进程概念: course/301258/resource/process-concept.md
              - 进程同步: course/301258/resource/synchronization.md
              - 存储管理: course/301258/resource/memorymanagement.md
              - 设备和文件管理: course/301258/resource/deviceandfilesystem.md
      - 操作系统原理实验:
          - 导引: course/301259/Readme.md
          - 周测习题集:
              - 周测6: course/301259/resource/week6.md
              - 周测11: course/301259/resource/week11.md
              - 周测12: course/301259/resource/week12.md
              - 周测13: course/301259/resource/week13.md
          - 模拟考试: course/301259/resource/mock.md
      - 计算机网络:
          - 导引: course/301214/Readme.md
          - 单元测验:
              - 数据链路层: course/301214/resource/datalinklayer.md
              - 网络层(一): course/301214/resource/networklayer1.md
              - 网络层(二): course/301214/resource/networklayer2.md
              - 运输层(一): course/301214/resource/transportlayer1.md
              - 运输层(二): course/301214/resource/transportlayer2.md
              - 应用层(一): course/301214/resource/applicationlayer1.md
              - 应用层(二): course/301214/resource/applicationlayer2.md
              - 网络安全: course/301214/resource/networksecurity.md
          - 期中期末:
              - 期中测验模拟: course/301214/resource/middleterm.md
              - 期末测验模拟: course/301214/resource/endterm.md
      - 计算机网络实验:
          - 导引: course/301215/Readme.md
          - 在线习题:
              - 测验1: course/301215/resource/test1.md
              - 测验2: course/301215/resource/test2.md
              - 测验4: course/301215/resource/test4.md
              - 测验5: course/301215/resource/test5.md
              - 测验6: course/301215/resource/test6.md
              - 测验7: course/301215/resource/test7.md
              - 测验9: course/301215/resource/test9.md
              - 测验10: course/301215/resource/test10.md
              - 测验11: course/301215/resource/test11.md
              - 测验12: course/301215/resource/test12.md
              - 测验13: course/301215/resource/test13.md
              - 测验15: course/301215/resource/test15.md
      - 数据库原理:
          - 导引: course/301102/Readme.md
  - PTA Solutions:
      - 简介: pta/Readme.md
      - 乙级考试练习:
          - 1001: pta/乙级考试练习/1001.md
          - 1002: pta/乙级考试练习/1002.md
          - 1003: pta/乙级考试练习/1003.md
          - 1004: pta/乙级考试练习/1004.md
          - 1005: pta/乙级考试练习/1005.md
          - 1006: pta/乙级考试练习/1006.md
          - 1007: pta/乙级考试练习/1007.md
          - 1008: pta/乙级考试练习/1008.md
          - 1009: pta/乙级考试练习/1009.md
      - 甲级考试练习:
          - 1001: pta/甲级考试练习/1001.md
          - 1002: pta/甲级考试练习/1002.md
          - 1003: pta/甲级考试练习/1003.md
          - 1004: pta/甲级考试练习/1004.md
          - 1005: pta/甲级考试练习/1005.md
          - 1006: pta/甲级考试练习/1006.md
          - 1007: pta/甲级考试练习/1007.md
          - 1008: pta/甲级考试练习/1008.md
          - 1009: pta/甲级考试练习/1009.md
  - 开发者文档:
      - Markdown扩展语法:
          - 警告框语法: help/markdown/admonition.md
          - 代码块扩展语法: help/markdown/codehilite.md
          - 其他扩展语法: help/markdown/others.md
      - 开发工具:
          - python管理项目: help/tools/python.md
          - git操作指南: help/tools/git.md
          - 文本编辑器: help/tools/vscode.md
          - 使用包管理器(可选): help/tools/package-manager.md
          - 命令行自动补全(可选): help/tools/cli.md
          - 题目制作器:
              - 快速入门: help/exercises-manager/quickstart.md
              - 深入了解命令行: help/exercises-manager/details.md

# Google Analytics(incompleted)
google_analytics:
  - "UA-XXXXXXXX-X"
  - "auto"
